### ISSUE TITLE
QA Filter Dropdown listing one person multiple times

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#161]
![image](https://cloud.githubusercontent.com/assets/15723101/17235603/8d3f5af0-5596-11e6-9821-87d1c8f2d024.png)

The same user is repeated 3 times.

Only one instance of that user needs to be selected for their changes to show. All three instances need removing to hide their changes.

**Comment by SPlanzer** [comment]
resolved please retest

**Comment by Deb-Jones** [comment]
Not fixed.

![image](https://cloud.githubusercontent.com/assets/15723101/18037540/31934f9c-6ddb-11e6-850f-5016fffcc966.png)

Low priority.
