### ISSUE TITLE
Refresh: Accepting last item on queue

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#195]
When the user accepts the last item on the queue, it can take some time to come off the queue and for the AIMS Review layer to update. The user thinks they haven't accepted and tries to accept again but gets an error that it's already being modfied.

There is no impact on data quality. It is just a frustration for users.

**Comment by billgeo** [comment]
@splanzer is this that bug you were working or already fixed?

**Comment by SPlanzer** [comment]
This is fixed awaiting testing prior to release

**Comment by linzbjones** [comment]
@SPlanzer Once tstassgeo1 is up and running can you please release this on test? Once release can you please assign to @Deb-Jones to test.

**Comment by Deb-Jones** [comment]
I still see this problem on production, but when I test on test I can't replicate it.
Happy to close for now, and reopen if it reoccurs once new version and 2.14.8 is rolled out to everyone.

**Comment by SPlanzer** [comment]
This is part of the 1.2.0 release (please test in dev version 1.1.0)
